### PR TITLE
Remove vjoin

### PR DESCRIPTION
**Pull request by mdonaka**
# Summary
Remove vjoin

# Purpose
To clarify the libclient interface

# Contents
- Remove vjoin
- Fix various tests using execute request

example
```python
# before
qmpc.get_join_table(([data_id1, data_id2], [2]))
# after
qmpc.get_join_table([data_id1, data_id2])
```

# Testing Methods Performed
- medium test
- CI

### CODE REVIEW

**Comment by mdonaka** [comment]
@KotaTakahashi9320 
I have modified the README.
Since there was no information on usage in `libclient-py/README.md`, I added it in `libclient-py/quikcmpc/README.md`.
[fa0cb59](https://github.com/acompany-develop/QuickMPC/pull/229/commits/fa0cb59209a49a0aa8f2b95aa2eb06a2302312c5)

**Comment by KotaTakahashi9320** [comment]
@mdonaka 
Thanks for the change!
What do you think it would be better to clearly state that it is an option?

**Comment by mdonaka** [comment]
@KotaTakahashi9320 
I added! [35d4eba](https://github.com/acompany-develop/QuickMPC/pull/229/commits/35d4eba6fda5f0d69f0c408a565e2da9a61c7874)

**Review by KotaTakahashi9320 — APPROVED** [review]
LGTM!

**Pull request merged**
