### PR TITLE
Remove extraneous error handling

### PR DESCRIPTION
**Pull request by KotaTakahashi9320**
# Summary
Remove extraneous error handling
# Purpose
Remove extraneous error handling
# Contents
Remove extraneous error handling
# Testing Methods Performed
CI

### CODE REVIEW

**Review by come2ry — APPROVED** [review]

**Review by arukuka — APPROVED** [review]
Thank you!

**Review by mdonaka — APPROVED** [review]
@KotaTakahashi9320 CC: @arukuka 
I want to merge #68  first, so please rebase after #68  merge.
The content is fine. Thanks!

**Comment by arukuka** [comment]
@KotaTakahashi9320 Sorry for late.  
I have merged #68 .  
Please rebase to latest main branch

**Comment by KotaTakahashi9320** [comment]
@arukuka 
Rebase to the latest main branch.
Please check it out

**Review by arukuka — APPROVED** [review]
Thank you!

**Pull request merged**
