### PR TITLE
Use JWT for CC-to-BTS communication

### PR DESCRIPTION
**Pull request by arukuka**
# Summary

- Use JWT for CC-to-BTS communication
- related to https://github.com/acompany-develop/QuickMPC-BTS/pull/4

# Purpose

- This PR resolves an internal-organization ticket.

# Contents

- Read JWT token from environment variables
- Set JWT token to gRPC context

# Testing Methods Performed

- Run demo with https://github.com/acompany-develop/QuickMPC-BTS/pull/4

### CODE REVIEW

**Comment by mdonaka** [comment]
@arukuka 
Was it intentional not to update the BTS version? (I saw the commit message)
https://github.com/acompany-develop/QuickMPC/blob/ecdcba15fbf637e7a85c417c3ea81557cbe7c8c3/Test/docker-compose.yml#L127

**Comment by arukuka** [comment]
@mdonaka  
After https://github.com/acompany-develop/QuickMPC-BTS/pull/1 was merged,  
BTS image is currently updated by commit on `main` or `develop` branch. :bow:  
We can push new image tag by hand, but I am wondering that it is necessary.

**Comment by mdonaka** [comment]
@arukuka 
I see! I understand.
> We can push new image tag by hand, but I am wondering that it is necessary.
No need to do it manually!

**Comment by mdonaka** [comment]
Small test is failed, please check it.

**Review by mdonaka — APPROVED** [review]

**Pull request merged**
