### PR TITLE
Support arm64

### PR DESCRIPTION
**Pull request by arukuka**
# Summary

M1 Mac development now possible

# Purpose

- Make QuickMPC multi-arch supported

# Contents

- Use `TARGETPLATFORM` for multi-arch build
- Use couchbase 7.1.1
- Use bazelisk as bazel launcher
- Update several packages, tools for multi-arch build

# Testing Methods Performed

- CI https://github.com/arukuka/QuickMPC/commit/143c62a8e705827f38bd56a8aecde17e83898c48
- local medium CC test on M1 Mac
- checked that an binary can be launched on `dep-runner` image

### CODE REVIEW

**Comment by arukuka** [comment]
I checked CI status.  I will check details later.

- steps containing bazel are failed
- steps pushing image to registry are failed because it seems to be not allowed

**Comment by arukuka** [comment]
@acompany-develop/coreengine  
I cannot run CI expected because protecting safety.  
After checking the changelist, could you please create a PR to check the CI status?

**Review by mdonaka — COMMENTED** [review]
I was curious about the maintenance perspective.
Is there any way to check the operation on a non-M1 machine?
Will future maintenance be the responsibility of the person with the M1 machine?

**Comment by mdonaka** [comment]
> I cannot run CI expected because protecting safety.
After checking the changelist, could you please create a PR to check the CI status?

@arukuka 
Sorry, I didn't understand... Why is this? What does it mean?

**Comment by arukuka** [comment]
@mdonaka 

> Is there any way to check the operation on a non-M1 machine?

I have to add test run on arm64.  
I will add it, so I make it draft.

However, GitHub Actions cannot run test on arm64 by default.
We need to use self-hosted runner, or use other CI service.

> Will future maintenance be the responsibility of the person with the M1 machine?

I think so.

> Sorry, I didn't understand... Why is this? What does it mean?

I opened this PR from forked repository because

- I wrote this using hobby time, so I think that using fork is better way, and
- I'd like to check that a flow run correctly when PR is opened from forked repository.

Also, PR from forked repositry cannot access secrets used in GitHub Actions.

- doc: https://docs.github.com/ja/actions/security-guides/security-hardening-for-github-actions#accessing-secrets
- actual behavior: https://github.com/acompany-develop/QuickMPC/runs/7934124110#step:3:7

I apologize for the inconvenience.

**Comment by mdonaka** [comment]
@arukuka 
It would be ideal to have a test, but If the person who has the M1 machine can maintain it responsibly, I think this PR is good.
I think the arm64 test addition can be a separate PR.

> I opened this PR from forked repository

I understood.

**Comment by arukuka** [comment]
@mdonaka  
Thank you.  I will add description about this support as "experimental" on README.  
After its commit, I will make this PR open.

**Pull request closed without merging**
