### PR TITLE
Complete protoc with one command.

### PR DESCRIPTION
**Pull request by KotaTakahashi9320**
# Summary
Complete protoc with one command
# Purpose
Because only the python gRPC generation code is in a separate directory, and we sometimes forget to generate it.
# Contents
Create Dockerfile for environment to run protoc
Create a shell script to compile proto files
Create Makefile
Fix README.md
# Testing Methods Performed
Execute the following command to confirm that gRPC code can be generated
```sh
make generate
make generate t=./hoge
```

### CODE REVIEW

**Comment by KotaTakahashi9320** [comment]
@mdonaka @arukuka 
If I install quickmpc with mypy-protobuf installed, the following error occurs
Should I update the package version?
```
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
mypy-protobuf 3.4.0 requires protobuf>=4.21.8, but you have protobuf 3.20.3 which is incompatible.
```

**Comment by KotaTakahashi9320** [comment]
@mdonaka 
Corrected based on your suggestion.
I would appreciate your confirmation.

**Comment by mdonaka** [comment]
@KotaTakahashi9320 
> If I install quickmpc with mypy-protobuf installed, the following error occurs
Should I update the package version in this PR?

Since `libclient-py` install is not needed to generate proto files, only `grpcio-tools` and `mypy-protobuf` are needed, why not remove `libclient-py` install and change it to do `grpcio-tools` and `mypy-protobuf` install?
Furthermore, if you remove the `mypy-protobuf` install (in Pipfile) on the libclient-py side, errors due to version differences will not occur.

**Review by mdonaka — APPROVED** [review]
Thank you! I appreciate it very much!

**Comment by mdonaka** [comment]
@KotaTakahashi9320 
Please rebase 🙏

**Pull request merged**
